import { db } from "./db";
import { videos, type InsertVideo } from "@shared/schema";
import { sql } from "drizzle-orm";

// Реальное видео с Bunny CDN (HLS)
// Embed: https://player.mediadelivery.net/embed/511135/32fd1294-ede8-40c4-8ac6-c58073edc03e
// HLS плейлист для HTML5 video
const VIDEO_URL = "https://vz-6f283eac-64a.b-cdn.net/32fd1294-ede8-40c4-8ac6-c58073edc03e/playlist.m3u8";

const SALES_REELS: InsertVideo[] = [
  {
    id: "s1",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Каждый день похож на вчера?",
    hook: "Стоп. Можно иначе.",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Каждый день похож на вчера? Застряли в рутине? Есть способ выйти из круга",
    descriptionFull: "Каждый день похож на вчера? Застряли в рутине? Есть способ выйти из круга. Вертикальные видео открывают новые возможности для тех, кто готов действовать. #вертикальноевидео #трафик",
    likeCount: 5214,
    shareCount: 1823,
    commentCount: 7,
    orderIndex: 0,
    comments: [
      { id: "c1-1", author: "Анна М.", text: "Это именно то, что мне нужно было услышать! 🔥", likes: 42, timestamp: "2ч" },
      { id: "c1-2", author: "Дмитрий К.", text: "Наконец-то понятное объяснение! Спасибо", likes: 28, timestamp: "5ч" },
    ]
  },
  {
    id: "s2",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Обычные люди и вертикальные видео",
    hook: "Не блогеры. Обычные.",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Обычные люди и вертикальные видео. Не нужно быть блогером, чтобы начать",
    descriptionFull: "Обычные люди и вертикальные видео. Не нужно быть блогером, чтобы начать. Обычные люди получают результаты с помощью простой системы создания контента.",
    likeCount: 4892,
    shareCount: 2105,
    commentCount: 3,
    orderIndex: 1,
  },
  {
    id: "s3",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Поворот: система, а не хаос",
    hook: "Просто следуй шагам",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Поворот: система, а не хаос. Система, которой легко следовать",
    descriptionFull: "Поворот: система, а не хаос. Система, которой легко следовать. Шаг за шагом от идеи до результата. Никакого хаоса — только чёткий план действий.",
    likeCount: 6347,
    shareCount: 3214,
    commentCount: 3,
    orderIndex: 2,
  },
  {
    id: "s4",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "ИИ ускоряет создание вертикальных видео",
    hook: "Без сложных съёмок",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "ИИ ускоряет создание вертикальных видео. ИИ делает 80% работы за вас",
    descriptionFull: "ИИ ускоряет создание вертикальных видео. ИИ делает 80% работы за вас. Создавайте контент быстрее с помощью современных инструментов искусственного интеллекта.",
    likeCount: 7891,
    shareCount: 4567,
    commentCount: 4,
    orderIndex: 3,
  },
  {
    id: "s5",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Люди находят вас сами",
    hook: "Органический охват работает",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Люди находят вас сами. Не вы ищете клиентов — они ищут вас",
    descriptionFull: "Люди находят вас сами. Не вы ищете клиентов — они ищут вас. Правильный контент привлекает целевую аудиторию автоматически. Органический трафик работает 24/7.",
    likeCount: 9234,
    shareCount: 5678,
    commentCount: 5,
    orderIndex: 4,
  },
  {
    id: "s6",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Пирамида трафика",
    hook: "Основа роста",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Пирамида трафика. Строится один раз — работает годами",
    descriptionFull: "Пирамида трафика. Строится один раз — работает годами. Системный подход к привлечению аудитории. Один раз настроил — получаешь результат постоянно.",
    likeCount: 11245,
    shareCount: 6789,
    commentCount: 6,
    orderIndex: 5,
  },
  {
    id: "s7",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Базовая механика",
    hook: "Система из 6 модулей",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Базовая механика. Пошаговый путь от новичка до результата",
    descriptionFull: "Базовая механика. Пошаговый путь от новичка до результата. 6 модулей, которые проведут вас от нуля до стабильного потока клиентов.",
    likeCount: 10567,
    shareCount: 5432,
    commentCount: 4,
    orderIndex: 6,
  },
  {
    id: "s8",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Узнай больше сейчас",
    hook: "Готов начать?",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Узнай больше сейчас. Бесплатные уроки помогут начать путь",
    descriptionFull: "Узнай больше сейчас. Бесплатные уроки помогут начать путь. Получи доступ к знаниям, которые изменят твой подход к привлечению клиентов.",
    likeCount: 12345,
    shareCount: 7890,
    commentCount: 5,
    orderIndex: 7,
    ctaText: "Начать бесплатное обучение",
  },
  {
    id: "s9",
    type: "sales",
    videoUrl: VIDEO_URL,
    title: "Первый шаг — сейчас",
    hook: "Время действовать",
    author: "MONETIA",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    descriptionBrief: "Первый шаг — сейчас. Готов начать? Первый шаг определяет всё",
    descriptionFull: "Готов начать? Первый шаг определяет всё. Начните свою пирамиду трафика прямо сейчас и измените свой подход к привлечению клиентов навсегда.",
    likeCount: 15892,
    shareCount: 7651,
    commentCount: 3,
    orderIndex: 8,
    ctaText: "Получить доступ сейчас",
    isFinal: 1,
  },
];

const LESSONS: InsertVideo[] = [
  {
    id: "l1",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М1. Что такое бесплатный вертикальный трафик",
    captionBrief: "Почему вертикальные видео — главный источник бесплатного трафика.",
    captionFull: "Экосистема Reels/Shorts/TikTok, роль первых 3 секунд, удержание, базовая логика публикаций.",
    nextCtaText: "Следующий урок",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 3456,
    shareCount: 987,
    orderIndex: 0,
  },
  {
    id: "l2",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М2. Формула сильного хука (0–3 сек)",
    captionBrief: "Хуки: боль, интрига, шок-факт. Визуальные приёмы.",
    captionFull: "Готовые шаблоны, примеры формулировок и тестирование удержания.",
    nextCtaText: "Следующий урок",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 2789,
    shareCount: 1124,
    orderIndex: 1,
  },
  {
    id: "l3",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М3. ИИ-инструменты для генерации видео",
    captionBrief: "Как собирать ролики без съёмки.",
    captionFull: "Скрипты, генерация кадров, озвучка, автоматизация публикаций. Рекомендации по весу и кодекам.",
    nextCtaText: "Следующий урок",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 4521,
    shareCount: 2043,
    orderIndex: 2,
  },
  {
    id: "l4",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М4. Публикация и сигналы алгоритмов",
    captionBrief: "Когда постить, как подписывать, что влияет на показ.",
    captionFull: "Хэштеги, сабтайтлы, ритм монтажа, первые 24 часа.",
    nextCtaText: "Следующий урок",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 3278,
    shareCount: 1456,
    orderIndex: 3,
  },
  {
    id: "l5",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М5. Безопасные практики и рост",
    captionBrief: "Как избежать блокировок и теневых банов.",
    captionFull: "Разогрев аккаунта, частота постов, взаимодействие с аудиторией, аналитика первой недели.",
    nextCtaText: "Следующий урок",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 3890,
    shareCount: 2134,
    orderIndex: 4,
  },
  {
    id: "l6",
    type: "lesson",
    videoUrl: VIDEO_URL,
    lessonTitle: "М6. Масштабирование и системность",
    captionBrief: "От разовых роликов к постоянному потоку трафика.",
    captionFull: "Контент-план, репосты, кросс-постинг, партнёрства, путь от первых лидов до устойчивой системы.",
    nextCtaText: "Получить доступ к программе",
    author: "MONETIA Академия",
    authorAvatar: "/attached_assets/AVATARmain1_1760658669977.webp",
    likeCount: 5234,
    shareCount: 3456,
    orderIndex: 5,
    isFinal: 1,
  },
];

const TESTIMONIALS: InsertVideo[] = [
  {
    id: "t1",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Мария",
    role: "Студент",
    highlight: "«Думала, что не получится — получилось»",
    orderIndex: 0,
  },
  {
    id: "t2",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Антон",
    role: "Предприниматель",
    highlight: "«Главное — начать и делать»",
    orderIndex: 1,
  },
  {
    id: "t3",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Елена",
    role: "Маркетолог",
    highlight: "«Трафик пошёл на 3-й день»",
    orderIndex: 2,
  },
  {
    id: "t4",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Дмитрий",
    role: "Фрилансер",
    highlight: "«Теперь не трачу на рекламу»",
    orderIndex: 3,
  },
  {
    id: "t5",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Анна",
    role: "Блогер",
    highlight: "«Первые подписчики за неделю»",
    orderIndex: 4,
  },
  {
    id: "t6",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Михаил",
    role: "Владелец бизнеса",
    highlight: "«Клиенты сами пишут теперь»",
    orderIndex: 5,
  },
  {
    id: "t7",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Ольга",
    role: "Копирайтер",
    highlight: "«Научилась за выходные»",
    orderIndex: 6,
  },
  {
    id: "t8",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Игорь",
    role: "Тренер",
    highlight: "«Заявок стало в 3 раза больше»",
    orderIndex: 7,
  },
  {
    id: "t9",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Светлана",
    role: "Дизайнер",
    highlight: "«Вижу реальный результат»",
    orderIndex: 8,
  },
  {
    id: "t10",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Алексей",
    role: "Консультант",
    highlight: "«Органика работает лучше таргета»",
    orderIndex: 9,
  },
  {
    id: "t11",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Наталья",
    role: "Психолог",
    highlight: "«Страх камеры прошёл»",
    orderIndex: 10,
  },
  {
    id: "t12",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Сергей",
    role: "Эксперт",
    highlight: "«Просто и понятно объяснили»",
    orderIndex: 11,
  },
  {
    id: "t13",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Юлия",
    role: "Коуч",
    highlight: "«Результат превзошёл ожидания»",
    orderIndex: 12,
  },
  {
    id: "t14",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Павел",
    role: "SMM-специалист",
    highlight: "«Больше не нужен платный трафик»",
    orderIndex: 13,
  },
  {
    id: "t15",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Виктория",
    role: "Риелтор",
    highlight: "«Клиенты идут потоком»",
    orderIndex: 14,
  },
  {
    id: "t16",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Андрей",
    role: "Фотограф",
    highlight: "«Теперь я на первой странице»",
    orderIndex: 15,
  },
  {
    id: "t17",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Кристина",
    role: "Стилист",
    highlight: "«Записи на месяц вперёд»",
    orderIndex: 16,
  },
  {
    id: "t18",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Максим",
    role: "Программист",
    highlight: "«Даже техники работают в маркетинге»",
    orderIndex: 17,
  },
  {
    id: "t19",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Екатерина",
    role: "Нутрициолог",
    highlight: "«Первые клиенты за 5 дней»",
    orderIndex: 18,
  },
  {
    id: "t20",
    type: "testimonial",
    videoUrl: VIDEO_URL,
    author: "Роман",
    role: "Автор курсов",
    highlight: "«Продажи выросли в 4 раза»",
    orderIndex: 19,
  },
];

async function seed() {
  try {
    console.log("[Seed] Starting database seed...");

    // Очистка существующих данных
    await db.delete(videos);
    console.log("[Seed] Cleared existing videos");

    // Вставка всех видео
    const allVideos = [...SALES_REELS, ...LESSONS, ...TESTIMONIALS];
    await db.insert(videos).values(allVideos);
    
    console.log(`[Seed] Inserted ${SALES_REELS.length} sales reels`);
    console.log(`[Seed] Inserted ${LESSONS.length} lessons`);
    console.log(`[Seed] Inserted ${TESTIMONIALS.length} testimonials`);
    console.log(`[Seed] Total: ${allVideos.length} videos`);
    console.log("[Seed] Database seeded successfully! ✅");

    process.exit(0);
  } catch (error) {
    console.error("[Seed] Error seeding database:", error);
    process.exit(1);
  }
}

seed();
